#!/bin/bash

set -e  # Exit on error

# Create build directory if it doesn't exist
if [ ! -d build ]; then
    echo "Creating build directory..."
    mkdir build
fi

cd build

echo "Running cmake..."
cmake ..

echo "Building project..."
make

echo "Running ./3-pi-cycle-pro ..."
./3-pi-cycle-pro 

