#!/bin/bash

set -e  # Exit on error

# Create build directory if it doesn't exist
if [ ! -d build ]; then
    echo "Creating build directory..."
    mkdir build
fi

cd build

echo "Running cmake..."
cmake ..

echo "Building project..."
make

echo "Running 1-get-binance-klines..."
./1-get-binance-klines

echo "Running 2-pi-cycle-indicator..."
./2-pi-cycle-indicator

